package com.microage.tickettool;

/* Created by: Brian Milne
 * Date: February 14, 2014
 * 
 * Description: This program is used by the Microage Executive Support 
 * technicians to track the work they perform. The program is linked to a
 * database that holds the client data and their computer information. This
 * information is automatically updated when a ticket is submitted. The program
 * generates an .xml file that is used by Clearview to import the data into its
 * system. The program has a feature to send an email copy of the excel file
 * but this feature was disabled to comply with the new Ontario Anti Span 
 * legislation.
 */

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Brian Milne
 */
public class Main extends javax.swing.JFrame {

    // Personal Variable Declaration
    public static Main main;
    
    
    /**
     * GUI class.
     */
    public Main() {
        
        initComponents();
        getContentPane().setBackground(Color.gray);

        Image icon = Toolkit.getDefaultToolkit().getImage("lib/icon.png");
        this.setIconImage(icon);
        setTitle("Rogers WGS Ticket Tool");
        setDefaults();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        email = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        technician = new javax.swing.JComboBox();
        tab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pcName = new javax.swing.JTextField();
        make = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        model = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        asset = new javax.swing.JTextField();
        serial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        issue = new javax.swing.JTextPane();
        resLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resolution = new javax.swing.JTextPane();
        jSeparator2 = new javax.swing.JSeparator();
        dssRadio = new javax.swing.JRadioButton();
        imacRadio = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        asset3 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        partNum2 = new javax.swing.JTextField();
        serial3 = new javax.swing.JTextField();
        make2 = new javax.swing.JComboBox();
        model3 = new javax.swing.JComboBox();
        jLabel51 = new javax.swing.JLabel();
        model2 = new javax.swing.JComboBox();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        asset2 = new javax.swing.JTextField();
        make3 = new javax.swing.JComboBox();
        jLabel60 = new javax.swing.JLabel();
        partNum3 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        serial2 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        chTicket = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pcName2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        desk = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        os2 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        admin2 = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        appList2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        pcName3 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        os3 = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        admin3 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        appList3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        dock = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        chTicket4 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        desk4 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        dock4 = new javax.swing.JCheckBox();
        jLabel54 = new javax.swing.JLabel();
        type4 = new javax.swing.JComboBox();
        jLabel56 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        serial4 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        asset4 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        partNum4 = new javax.swing.JTextField();
        pcName4 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        model4 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        make4 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        Calendar cal = Calendar.getInstance();
        DateFormat dateFormat2 = new SimpleDateFormat("dd/MM/yyyy hh:ss");
        Date initDate = cal.getTime();
        startDate = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        endDate = new javax.swing.JSpinner();
        actionTaken = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        reoccurence = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        confirmClose = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        clientName = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        location = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        floor = new javax.swing.JComboBox();
        requesterButton = new javax.swing.JButton();
        requester = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        notification = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        saveSettings = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        clearMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        logs = new javax.swing.JMenuItem();
        modifyMenu = new javax.swing.JMenu();
        addUpdateMenu = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImages(null);

        email.setBackground(new java.awt.Color(102, 102, 102));
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email");
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Technician:");

        technician.setBackground(new java.awt.Color(102, 102, 102));
        technician.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Brian Milne", "Brent Phillips", "Frank Varano", "Marc Gwisdek", "Michael Wan", "Ryan Somerville", "Shaun Glew" }));

        tab.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                System.out.println("Tab: " + tab.getSelectedIndex());
            }
        });

        jPanel2.setBackground(java.awt.Color.gray);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Model:");

        pcName.setBackground(new java.awt.Color(102, 102, 102));
        pcName.setForeground(new java.awt.Color(255, 255, 255));

        make.setBackground(new java.awt.Color(102, 102, 102));
        make.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HP", "Apple", "Blackberry", "Samsung", "Monitor", "Other" }));
        make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Make:");

        model.setBackground(new java.awt.Color(102, 102, 102));
        model.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GEN_LAPTOP_HP", "6930p", "8440p", "8460p", "8470p", "8510w", "2530p", "2540p", "2560p", "2570p", "9470m", "840", "820", "GEN_DESKTOP_HP", "dc5100", "6000 Pro", "600 G1", "6200 Pro", "6300 Pro", "8200 Elite", "dc5700", "dc5800", "8100 Elite" }));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("S/N:");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("PC Name:");

        asset.setBackground(new java.awt.Color(102, 102, 102));
        asset.setForeground(new java.awt.Color(255, 255, 255));

        serial.setBackground(new java.awt.Color(102, 102, 102));
        serial.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Asset Tag:");

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Issue");

        issue.setBackground(new java.awt.Color(102, 102, 102));
        issue.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        issue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                issueKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(issue);

        resLabel.setForeground(new java.awt.Color(255, 255, 255));
        resLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resLabel.setText("Resolution");

        resolution.setBackground(new java.awt.Color(102, 102, 102));
        resolution.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resolutionKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(resolution);

        buttonGroup1.add(dssRadio);
        dssRadio.setForeground(new java.awt.Color(255, 255, 255));
        dssRadio.setText("DSS");

        buttonGroup1.add(imacRadio);
        imacRadio.setForeground(new java.awt.Color(255, 255, 255));
        imacRadio.setText("IMAC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(make, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serial, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asset, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pcName, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dssRadio)
                .addGap(43, 43, 43)
                .addComponent(imacRadio)
                .addGap(306, 306, 306))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(pcName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(make, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imacRadio)
                    .addComponent(dssRadio))
                .addContainerGap())
        );

        tab.addTab("DSS/IMAC", jPanel2);

        jPanel4.setBackground(java.awt.Color.gray);

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Model:");

        asset3.setBackground(new java.awt.Color(102, 102, 102));
        asset3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Model:");

        partNum2.setBackground(new java.awt.Color(102, 102, 102));
        partNum2.setForeground(new java.awt.Color(255, 255, 255));
        partNum2.setToolTipText("C7Q19AW#ABA");

        serial3.setBackground(new java.awt.Color(102, 102, 102));
        serial3.setForeground(new java.awt.Color(255, 255, 255));

        make2.setBackground(new java.awt.Color(102, 102, 102));
        make2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HP" }));
        make2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                make2ActionPerformed(evt);
            }
        });

        model3.setBackground(new java.awt.Color(102, 102, 102));
        model3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GEN_LAPTOP_HP", "6930p", "8440p", "8460p", "8470p", "8510w", "2530p", "2540p", "2560p", "2570p", "9470m", "840", "820", "GEN_DESKTOP_HP", "dc5100", "6000 Pro", "600 G1", "6200 Pro", "6300 Pro", "8200 Elite", "dc5700", "dc5800", "8100 Elite" }));

        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Make:");

        model2.setBackground(new java.awt.Color(102, 102, 102));
        model2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GEN_LAPTOP_HP", "6930p", "8440p", "8460p", "8470p", "8510w", "2530p", "2540p", "2560p", "2570p", "9470m", "840", "820", "GEN_DESKTOP_HP", "dc5100", "6000 Pro", "600 G1", "6200 Pro", "6300 Pro", "8200 Elite", "dc5700", "dc5800", "8100 Elite" }));

        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("S/N:");

        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("S/N:");

        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Part No:");

        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Part No:");

        asset2.setBackground(new java.awt.Color(102, 102, 102));
        asset2.setForeground(new java.awt.Color(255, 255, 255));

        make3.setBackground(new java.awt.Color(102, 102, 102));
        make3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HP", "Other" }));
        make3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                make3ActionPerformed(evt);
            }
        });

        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Asset Tag:");

        partNum3.setBackground(new java.awt.Color(102, 102, 102));
        partNum3.setForeground(new java.awt.Color(255, 255, 255));
        partNum3.setToolTipText("C7Q19AW#ABA");

        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Make:");

        serial2.setBackground(new java.awt.Color(102, 102, 102));
        serial2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Asset Tag:");

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Ticket #:");

        chTicket.setBackground(new java.awt.Color(102, 102, 102));
        chTicket.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PC Name:");

        pcName2.setBackground(new java.awt.Color(102, 102, 102));
        pcName2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Pillar & Pod No:");

        desk.setBackground(new java.awt.Color(102, 102, 102));
        desk.setForeground(new java.awt.Color(255, 255, 255));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("OS:");

        os2.setBackground(new java.awt.Color(102, 102, 102));
        os2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Win 7", "Win XP" }));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Local Admin:");

        admin2.setBackground(new java.awt.Color(102, 102, 102));
        admin2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N", "Y" }));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Application List:");

        appList2.setBackground(new java.awt.Color(102, 102, 102));
        appList2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("PC Name:");

        pcName3.setBackground(new java.awt.Color(102, 102, 102));
        pcName3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("OS:");

        os3.setBackground(new java.awt.Color(102, 102, 102));
        os3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Win 7", "Win XP" }));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Local Admin:");

        admin3.setBackground(new java.awt.Color(102, 102, 102));
        admin3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "N", "Y" }));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Application List:");

        appList3.setBackground(new java.awt.Color(102, 102, 102));
        appList3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("New Computer");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Old Computer");

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Docking Station Provided?:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel61)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(make3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(model3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serial3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel60)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(asset3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(partNum3))
                    .addComponent(jSeparator8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(make2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel49))
                            .addComponent(pcName2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(model2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(serial2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel63)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(asset2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(partNum2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(os2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(admin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(appList2))))
                    .addComponent(jSeparator1)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desk, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dock))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pcName3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(os3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appList3)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dock)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(chTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(desk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(jLabel49)
                    .addComponent(jLabel52)
                    .addComponent(serial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63)
                    .addComponent(model2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55)
                    .addComponent(partNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(make2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asset2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pcName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(os2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(admin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(appList2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(make3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50)
                    .addComponent(jLabel53)
                    .addComponent(serial3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asset3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(model3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57)
                    .addComponent(partNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(pcName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(os3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(admin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(appList3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tab.addTab("PC Refresh", jPanel4);

        jPanel3.setBackground(java.awt.Color.gray);

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Ticket #:");

        chTicket4.setBackground(new java.awt.Color(102, 102, 102));
        chTicket4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Pillar & Pod No:");

        desk4.setBackground(new java.awt.Color(102, 102, 102));
        desk4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Docking Station Provided?:");

        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Type:");

        type4.setBackground(new java.awt.Color(102, 102, 102));
        type4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laptop", "Desktop", "Tablet", "Other" }));

        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Model:");

        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("S/N:");

        serial4.setBackground(new java.awt.Color(102, 102, 102));
        serial4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("New Computer");

        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Asset Tag:");

        asset4.setBackground(new java.awt.Color(102, 102, 102));
        asset4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Part No:");

        partNum4.setBackground(new java.awt.Color(102, 102, 102));
        partNum4.setForeground(new java.awt.Color(255, 255, 255));
        partNum4.setToolTipText("C7Q19AW#ABA");

        pcName4.setBackground(new java.awt.Color(102, 102, 102));
        pcName4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("PC Name:");

        model4.setBackground(new java.awt.Color(102, 102, 102));
        model4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Make:");

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Description");

        description.setBackground(new java.awt.Color(102, 102, 102));
        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        make4.setBackground(new java.awt.Color(102, 102, 102));
        make4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GEN_EQUIPMENT", "840", "820", "9470m", "iPad Air", "Galaxy Note 3" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(partNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel40)
                                .addGap(4, 4, 4)
                                .addComponent(pcName4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(type4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(make4, 0, 113, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel56)
                                .addGap(4, 4, 4)
                                .addComponent(model4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(serial4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel64)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(asset4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chTicket4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desk4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dock4))
                    .addComponent(description))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dock4)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(chTicket4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel34)
                        .addComponent(desk4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(jLabel56)
                    .addComponent(jLabel58)
                    .addComponent(serial4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64)
                    .addComponent(type4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asset4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(model4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(make4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(pcName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59)
                    .addComponent(partNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tab.addTab("New Installs", jPanel3);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Start Time:");

        startDate.setModel(new javax.swing.SpinnerDateModel());

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Status:");

        status.setBackground(new java.awt.Color(102, 102, 102));
        status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Closed", "Open", "Open - SLA Hold" }));
        status.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                statusItemStateChanged(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Completion Time:");

        endDate.setModel(new javax.swing.SpinnerDateModel());

        actionTaken.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Action Taken:");

        reoccurence.setBackground(new java.awt.Color(102, 102, 102));
        reoccurence.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        reoccurence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reoccurenceActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Reoccurence:");

        confirmClose.setBackground(new java.awt.Color(102, 102, 102));
        confirmClose.setForeground(new java.awt.Color(255, 255, 255));
        confirmClose.setText("Confirm Closed?");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Client's Name:");

        clientName.setBackground(new java.awt.Color(102, 102, 102));
        clientName.setForeground(new java.awt.Color(255, 255, 255));
        clientName.setToolTipText("John Smith");
        clientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientNameActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(102, 102, 102));
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Title:");

        title.setBackground(new java.awt.Color(102, 102, 102));
        title.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Location:");

        location.setBackground(new java.awt.Color(102, 102, 102));
        location.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OMP", "333 Bloor", "350 Bloor", "Brampton", "Other", "" }));
        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Floor:");

        floor.setBackground(new java.awt.Color(102, 102, 102));
        floor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));

        requesterButton.setBackground(new java.awt.Color(102, 102, 102));
        requesterButton.setForeground(new java.awt.Color(255, 255, 255));
        requesterButton.setText("Search");
        requesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requesterButtonActionPerformed(evt);
            }
        });

        requester.setBackground(new java.awt.Color(102, 102, 102));
        requester.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Requester:");

        notification.setBackground(new java.awt.Color(102, 102, 102));
        notification.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Email", "Phone Call", "Shoulder Tap", "ISM" }));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Notification:");

        phone.setBackground(new java.awt.Color(102, 102, 102));
        phone.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone #:");

        jMenuBar2.setBackground(new java.awt.Color(255, 255, 255));

        jMenu3.setText("File");

        saveSettings.setText("Save Settings");
        saveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSettingsActionPerformed(evt);
            }
        });
        jMenu3.add(saveSettings);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu3.add(exit);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");

        clearMenu.setText("Clear");
        clearMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMenuActionPerformed(evt);
            }
        });
        jMenu4.add(clearMenu);

        jMenuBar2.add(jMenu4);

        jMenu1.setText("View");

        logs.setText("Logs");
        logs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logsActionPerformed(evt);
            }
        });
        jMenu1.add(logs);

        jMenuBar2.add(jMenu1);

        modifyMenu.setText("Modify Database");

        addUpdateMenu.setText("Add/Update Client");
        addUpdateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUpdateMenuActionPerformed(evt);
            }
        });
        modifyMenu.add(addUpdateMenu);

        jMenuBar2.add(modifyMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(technician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(notification, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(requester, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(requesterButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confirmClose)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reoccurence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actionTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel2)
                        .addComponent(searchButton)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(notification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(requesterButton)
                    .addComponent(requester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(reoccurence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(actionTaken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(jLabel15)
                    .addComponent(technician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(1);
    }//GEN-LAST:event_exitActionPerformed

    private void clientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientNameActionPerformed

        clientName.addActionListener(new ActionListener(){

                public void actionPerformed(ActionEvent e){

                        searchButtonActionPerformed(e);

                }});
    }//GEN-LAST:event_clientNameActionPerformed
    
    // Sends the email to the Microage coordinator.
    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // Check for mandatory fields
        if (clientName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Client Name is a mandatory field", "Missing field", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (location.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Location is a mandatory field", "Missing field", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (notification.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Notification is a mandatory field", "Missing field", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (issue.getText().isEmpty() && tab.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "The issue field is mandatory.", "Missing field", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (tab.getSelectedIndex() == 1) 
            if (chTicket.getText().isEmpty() || desk.getText().isEmpty() || serial2.getText().isEmpty() || 
                asset2.getText().isEmpty() || partNum2.getText().isEmpty() || pcName2.getText().isEmpty() || 
                serial3.getText().isEmpty() || asset3.getText().isEmpty() || partNum3.getText().isEmpty() || 
                pcName3.getText().isEmpty() ) {
                JOptionPane.showMessageDialog(null, "All fields are mandator for PC Refresh requests.", "Missing field", JOptionPane.ERROR_MESSAGE);
                return;
            }
        if (tab.getSelectedIndex() == 2) {
            if (chTicket4.getText().isEmpty() || desk4.getText().isEmpty() || serial4.getText().isEmpty() || 
                asset4.getText().isEmpty() || partNum4.getText().isEmpty() || pcName4.getText().isEmpty() || 
                make4.getSelectedItem() == "" || description.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "All fields are mandator for New Install requests.", "Missing field", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if (!dssRadio.isSelected() && !imacRadio.isSelected() && tab.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Choose the type of ticket DSS or IMAC.", "Missing type", JOptionPane.ERROR_MESSAGE);
            return;
        }

        SimpleDateFormat format = new SimpleDateFormat("yyMMddHHmm"); 
        String formattedStartDate = format.format((Date)startDate.getValue());
        String formattedEndDate = format.format((Date)endDate.getValue());
        // Check date.
        if (formattedStartDate.compareTo(formattedEndDate) >= 0) {
            JOptionPane.showMessageDialog(null, "Start date must precede the end date.", "Date Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Check contract end date.
        if (Integer.parseInt(format.format(new Date())) > 1412130000) {
            JOptionPane.showMessageDialog(null, "Error code 1337", "Fatal Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Check SLA
        if (Integer.parseInt(format.format((Date)endDate.getValue())) - Integer.parseInt(format.format((Date)startDate.getValue())) > 400) {
            JOptionPane.showMessageDialog(null, "Ticket out of SLA. Please check your time.", "Date Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        AutoUpdateDB.AutoUpdateDB();
        
        // ************* End Update Database ************************
        CreateXLS.CreateXLS("i:\\Rogers\\Tickets\\");
        CreateXLS.CreateXLS("W:\\WGSImport\\");
        
        // Send email to coordinators and tech.
        SendEmail.SendEmail();

        final ImageIcon icon = new ImageIcon("lib\\mail.png");
        Image img = icon.getImage();  
        Image newimg = img.getScaledInstance(100, 100,  java.awt.Image.SCALE_SMOOTH);  
        ImageIcon newIcon = new ImageIcon(newimg); 
        JOptionPane.showMessageDialog(null, "CV Ticket Generated.", "Ticket Created", JOptionPane.INFORMATION_MESSAGE, newIcon);
        clear();
    }//GEN-LAST:event_emailActionPerformed

    private void clear() {
        clientName.setText("");
        title.setText("");            
        location.setSelectedItem("");
        floor.setSelectedItem("");
        requester.setText("");
        phone.setText("");
        model.setSelectedItem("");
        serial.setText("");
        asset.setText("");
        pcName.setText("");
        model2.setSelectedItem("");
        serial2.setText("");
        asset2.setText("");
        pcName2.setText("");
        partNum2.setText("");
        appList2.setText("");
        model3.setSelectedItem("");
        serial3.setText("");
        asset3.setText("");
        pcName3.setText("");
        partNum3.setText("");
        appList3.setText("");
        chTicket.setText("");
        desk.setText("");
        chTicket4.setText("");
        desk4.setText("");
        dock4.setSelected(false);
        make4.setSelectedItem("");
        model4.setText("");
        serial4.setText("");
        asset4.setText("");
        partNum4.setText("");
        pcName4.setText("");
        description.setText("");
        issue.setText("");
        resolution.setText("");
        status.setSelectedItem("Closed");
        buttonGroup1.clearSelection();
        dock.setSelected(false);
        confirmClose.setSelected(false);
        notification.setSelectedIndex(0);
        
        // Check for settings.ini file and loads in default settings.
        setDefaults();
    } 
    
    private void clearMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMenuActionPerformed
        clear();
    }//GEN-LAST:event_clearMenuActionPerformed

    private void setDefaults() {
        actionTaken.setEditable(false);
        actionTaken.setBackground(Color.GRAY);
        reoccurence.setSelectedItem("No");
        File f = new File("i:\\Rogers\\settings.ini");
        if(f.exists()) {
            try {
                BufferedReader br = new BufferedReader(new FileReader(f));
                technician.setSelectedItem(br.readLine());
                br.close();
            }
            catch (Exception e) {
                System.out.println(e);
            }
        }
    }
    
    // Backs up the technicians personal settings.
    private void saveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSettingsActionPerformed
        new File("i:\\Rogers").mkdirs();
        try {
	    FileWriter writer = new FileWriter("i:\\Rogers\\settings.ini");
            writer.append((String)technician.getSelectedItem());
	    writer.flush();
	    writer.close();
	}
	catch(IOException e) {
	     e.printStackTrace();
	} 
    }//GEN-LAST:event_saveSettingsActionPerformed

    // Enable the tab key to switch focus.
    private void issueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_issueKeyPressed
    	if(evt.getKeyCode() == KeyEvent.VK_TAB) {
    		if(evt.getModifiers() > 0) issue.transferFocusBackward();
    		else issue.transferFocus();	
    		evt.consume();
    	}
    }//GEN-LAST:event_issueKeyPressed

    // Enable the tab key to switch focus.
    private void resolutionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resolutionKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_TAB) {
            if(evt.getModifiers() > 0) resolution.transferFocusBackward();
            else resolution.transferFocus();	
            evt.consume();
    	}
    }//GEN-LAST:event_resolutionKeyPressed

    private void logsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsActionPerformed
        new File("i:\\Rogers\\Tickets").mkdirs();
        File file = new File ("i:\\Rogers\\Tickets");
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.open(file);
        }
        catch (Exception e) {
            System.out.println("Unable to open log location. " + e);
        }
    }//GEN-LAST:event_logsActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        SearchDB.SearchDB();
    }//GEN-LAST:event_searchButtonActionPerformed
    
    private void requesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requesterButtonActionPerformed
        SearchDB.SearchRequesterDB();
    }//GEN-LAST:event_requesterButtonActionPerformed

    private void reoccurenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reoccurenceActionPerformed
        if (reoccurence.getSelectedItem() == "Yes") {
            actionTaken.setEditable(true);
            actionTaken.setBackground(Color.WHITE);
        } else {
            actionTaken.setEditable(false);
            actionTaken.setText("");
            actionTaken.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_reoccurenceActionPerformed
    
    private void statusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_statusItemStateChanged
        if (status.getSelectedItem() != "Closed") {
            confirmClose.setSelected(false);
            confirmClose.setEnabled(false);
            reoccurence.setEnabled(false);
            jLabel18.setEnabled(false);
            jLabel19.setEnabled(false);
        }
        else { 
            confirmClose.setEnabled(true);
            reoccurence.setEnabled(true);
            jLabel18.setEnabled(true);
            jLabel19.setEnabled(true);
        }
    }//GEN-LAST:event_statusItemStateChanged

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        String[] OMPArray = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
            "11", "12", "13", "14", "15", "16", "" };
        DefaultComboBoxModel OMPModel = new DefaultComboBoxModel( OMPArray );
        String[] b333Array = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "" };
        DefaultComboBoxModel b333Model = new DefaultComboBoxModel( b333Array );
        String[] b350Array = { "1", "2", "3", "4", "5", "6", "" };
        DefaultComboBoxModel b350Model = new DefaultComboBoxModel( b350Array );
        String[] bramptonArray = { "City Center", "North Building 1st FL", 
            "North Building 2nd FL", "Networking Building", "East Building 1st FL", 
            "East Building 2nd FL", "East Building 3rd FL", "South Building 2nd FL", ""
        };
        DefaultComboBoxModel bramptonModel = new DefaultComboBoxModel( bramptonArray );
        String[] otherArray = { "855 York Mills", "1 Blue Jays Way", "Other", "" };
        DefaultComboBoxModel otherModel = new DefaultComboBoxModel( otherArray );
         
        if (location.getSelectedItem().equals("OMP")) {
            floor.setModel(OMPModel);
        } else if (location.getSelectedItem().equals("333 Bloor")) {
            floor.setModel(b333Model);
        } else if (location.getSelectedItem().equals("350 Bloor")) {
            floor.setModel(b350Model);
        } else if (location.getSelectedItem().equals("Brampton")) {
            floor.setModel(bramptonModel);
        } else if (location.getSelectedItem().equals("Other")) {
            floor.setModel(otherModel);
        } 
    }//GEN-LAST:event_locationActionPerformed

    private void make3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make3ActionPerformed
        String[] hpModelArray = { "GEN_LAPTOP_HP", "6930p", "8440p", "8460p", "8470p", "8510w", "2530p",
            "2540p", "2560p", "2570p", "9470m", "840", "820", "GEN_DESKTOP_HP", "dc5100", "6000 Pro",
            "600 G1", "6200 Pro", "6300 Pro", "8200 Elite", "dc5700", "dc5800", "8100 Elite"};
        DefaultComboBoxModel hpModel = new DefaultComboBoxModel( hpModelArray );
        String[] monitorArray = { "GEN_MONITOR_HP", "LA1951", "L1940T", "LP2465"};
        DefaultComboBoxModel monitorModel = new DefaultComboBoxModel( monitorArray );
        String[] appleModelArray = { "GEN_MAC" , "IPHONE", "iPhone 4", "iPhone 4s",
            "iPhone 5", "iPhone 5s", "iPhone 5c", "iPhone 6", "iPhone 6 Plus", "IPAD", "IPAD2", "IPAD3", "IPAD4",
            "iPad Mini", "IPAD AIR" };
        DefaultComboBoxModel appleModel = new DefaultComboBoxModel( appleModelArray );
        String[] samsungModelArray = { "Galaxy", "Galaxy S4", "Galaxy S5", "Galaxy Note",
            "Galaxy Note 2", "Galaxy Note 3", "Galaxy Tab", "Galaxy Tab 2", "Galaxy Tab 3" };
        DefaultComboBoxModel samsungModel = new DefaultComboBoxModel( samsungModelArray );
        String[] bbModelArray = { "Blackberry", "Blackberry Q10", "Blackberry Q5",
            "Blackberry Z10", "Blackberry Z30", "BlackBerry 8900", "BlackBerry 9900",
            "BlackBerry 9000", "Playbook" };
        DefaultComboBoxModel bbModel = new DefaultComboBoxModel( bbModelArray );
        String[] defModelArray = { "GEN_EQUIPMENT", "GEN_PDA_EQUIPMENT" };
        DefaultComboBoxModel defModel = new DefaultComboBoxModel( defModelArray );

        if (make3.getSelectedItem().equals("HP")) {
            model3.setModel(hpModel);
        } else if (make3.getSelectedItem().equals("Apple")) {
            model3.setModel(appleModel);
        } else if (make3.getSelectedItem().equals("Blackberry")) {
            model3.setModel(bbModel);
        } else if (make3.getSelectedItem().equals("Samsung")) {
            model3.setModel(samsungModel);
        } else if (make3.getSelectedItem().equals("Monitor")) {
            model3.setModel(monitorModel);
        } else if (make3.getSelectedItem().equals("Other")) {
            model3.setModel(defModel);
        }
        serial3.setText("");
        asset3.setText("");
        pcName3.setText("");
    }//GEN-LAST:event_make3ActionPerformed

    private void make2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make2ActionPerformed
        String[] hpModelArray = { "GEN_LAPTOP_HP", "6930p", "8440p", "8460p", "8470p", "8510w", "2530p",
            "2540p", "2560p", "2570p", "9470m", "840", "820", "GEN_DESKTOP_HP", "dc5100", "6000 Pro",
            "600 G1", "6200 Pro", "6300 Pro", "8200 Elite", "dc5700", "dc5800", "8100 Elite"};
        DefaultComboBoxModel hpModel = new DefaultComboBoxModel( hpModelArray );
        String[] monitorArray = { "GEN_MONITOR_HP", "LA1951", "L1940T", "LP2465"};
        DefaultComboBoxModel monitorModel = new DefaultComboBoxModel( monitorArray );
        String[] appleModelArray = { "GEN_MAC" , "IPHONE", "iPhone 4", "iPhone 4s",
            "iPhone 5", "iPhone 5s", "iPhone 5c", "iPhone 6", "iPhone 6 Plus", "IPAD", "IPAD2", "IPAD3", "IPAD4",
            "iPad Mini", "IPAD AIR" };
        DefaultComboBoxModel appleModel = new DefaultComboBoxModel( appleModelArray );
        String[] samsungModelArray = { "Galaxy", "Galaxy S4", "Galaxy S5", "Galaxy Note",
            "Galaxy Note 2", "Galaxy Note 3", "Galaxy Tab", "Galaxy Tab 2", "Galaxy Tab 3" };
        DefaultComboBoxModel samsungModel = new DefaultComboBoxModel( samsungModelArray );
        String[] bbModelArray = { "Blackberry", "Blackberry Q10", "Blackberry Q5",
            "Blackberry Z10", "Blackberry Z30", "BlackBerry 8900", "BlackBerry 9900",
            "BlackBerry 9000", "Playbook" };
        DefaultComboBoxModel bbModel = new DefaultComboBoxModel( bbModelArray );
        String[] defModelArray = { "GEN_EQUIPMENT", "GEN_PDA_EQUIPMENT" };
        DefaultComboBoxModel defModel = new DefaultComboBoxModel( defModelArray );

        if (make2.getSelectedItem().equals("HP")) {
            model2.setModel(hpModel);
        } else if (make2.getSelectedItem().equals("Apple")) {
            model2.setModel(appleModel);
        } else if (make2.getSelectedItem().equals("Blackberry")) {
            model2.setModel(bbModel);
        } else if (make2.getSelectedItem().equals("Samsung")) {
            model2.setModel(samsungModel);
        } else if (make2.getSelectedItem().equals("Monitor")) {
            model2.setModel(monitorModel);
        } else if (make2.getSelectedItem().equals("Other")) {
            model2.setModel(defModel);
        }
        serial2.setText("");
        asset2.setText("");
    }//GEN-LAST:event_make2ActionPerformed

    private void makeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeActionPerformed

        String[] hpModelArray = { "GEN_LAPTOP_HP", "6930p", "8440p", "8460p", "8470p", "8510w", "2530p",
            "2540p", "2560p", "2570p", "9470m", "840", "820", "GEN_DESKTOP_HP", "dc5100", "6000 Pro",
            "600 G1", "6200 Pro", "6300 Pro", "8200 Elite", "dc5700", "dc5800", "8100 Elite"};
        DefaultComboBoxModel hpModel = new DefaultComboBoxModel( hpModelArray );
        String[] monitorArray = { "GEN_MONITOR_HP", "LA1951", "L1940T", "LP2465"};
        DefaultComboBoxModel monitorModel = new DefaultComboBoxModel( monitorArray );
        String[] appleModelArray = { "GEN_MAC" , "IPHONE", "iPhone 4", "iPhone 4s",
            "iPhone 5", "iPhone 5s", "iPhone 5c", "iPhone 6", "iPhone 6 Plus", "IPAD", "IPAD2", "IPAD3", "IPAD4",
            "iPad Mini", "IPAD AIR" };
        DefaultComboBoxModel appleModel = new DefaultComboBoxModel( appleModelArray );
        String[] samsungModelArray = { "Galaxy", "Galaxy S4", "Galaxy S5", "Galaxy Note",
            "Galaxy Note 2", "Galaxy Note 3", "Galaxy Tab", "Galaxy Tab 2", "Galaxy Tab 3" };
        DefaultComboBoxModel samsungModel = new DefaultComboBoxModel( samsungModelArray );
        String[] bbModelArray = { "Blackberry", "Blackberry Q10", "Blackberry Q5",
            "Blackberry Z10", "Blackberry Z30", "BlackBerry 8900", "BlackBerry 9900",
            "BlackBerry 9000", "Playbook" };
        DefaultComboBoxModel bbModel = new DefaultComboBoxModel( bbModelArray );
        String[] defModelArray = { "GEN_EQUIPMENT", "GEN_PDA_EQUIPMENT" };
        DefaultComboBoxModel defModel = new DefaultComboBoxModel( defModelArray );

        if (make.getSelectedItem().equals("HP")) {
            model.setModel(hpModel);
        } else if (make.getSelectedItem().equals("Apple")) {
            model.setModel(appleModel);
        } else if (make.getSelectedItem().equals("Blackberry")) {
            model.setModel(bbModel);
        } else if (make.getSelectedItem().equals("Samsung")) {
            model.setModel(samsungModel);
        } else if (make.getSelectedItem().equals("Monitor")) {
            model.setModel(monitorModel);
        } else if (make.getSelectedItem().equals("Other")) {
            model.setModel(defModel);
        }
        serial.setText("");
        asset.setText("");
        pcName.setText("");
    }//GEN-LAST:event_makeActionPerformed

    private void addUpdateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUpdateMenuActionPerformed
        AutoUpdateDB.AutoUpdateDB();
    }//GEN-LAST:event_addUpdateMenuActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main = new Main();
                main.setVisible(true);
            }
        });        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField actionTaken;
    private javax.swing.JMenuItem addUpdateMenu;
    protected javax.swing.JComboBox admin2;
    protected javax.swing.JComboBox admin3;
    protected javax.swing.JTextField appList2;
    protected javax.swing.JTextField appList3;
    protected javax.swing.JTextField asset;
    protected javax.swing.JTextField asset2;
    protected javax.swing.JTextField asset3;
    protected javax.swing.JTextField asset4;
    private javax.swing.ButtonGroup buttonGroup1;
    protected javax.swing.JTextField chTicket;
    protected javax.swing.JTextField chTicket4;
    private javax.swing.JMenuItem clearMenu;
    protected javax.swing.JTextField clientName;
    protected javax.swing.JCheckBox confirmClose;
    protected javax.swing.JTextField description;
    protected javax.swing.JTextField desk;
    protected javax.swing.JTextField desk4;
    protected javax.swing.JCheckBox dock;
    protected javax.swing.JCheckBox dock4;
    protected javax.swing.JRadioButton dssRadio;
    private javax.swing.JButton email;
    protected javax.swing.JSpinner endDate;
    private javax.swing.JMenuItem exit;
    protected javax.swing.JComboBox floor;
    protected javax.swing.JRadioButton imacRadio;
    protected javax.swing.JTextPane issue;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    protected javax.swing.JComboBox location;
    private javax.swing.JMenuItem logs;
    protected javax.swing.JComboBox make;
    protected javax.swing.JComboBox make2;
    protected javax.swing.JComboBox make3;
    protected javax.swing.JComboBox make4;
    protected javax.swing.JComboBox model;
    protected javax.swing.JComboBox model2;
    protected javax.swing.JComboBox model3;
    protected javax.swing.JTextField model4;
    private javax.swing.JMenu modifyMenu;
    protected javax.swing.JComboBox notification;
    protected javax.swing.JComboBox os2;
    protected javax.swing.JComboBox os3;
    protected javax.swing.JTextField partNum2;
    protected javax.swing.JTextField partNum3;
    protected javax.swing.JTextField partNum4;
    protected javax.swing.JTextField pcName;
    protected javax.swing.JTextField pcName2;
    protected javax.swing.JTextField pcName3;
    protected javax.swing.JTextField pcName4;
    protected javax.swing.JTextField phone;
    protected javax.swing.JComboBox reoccurence;
    protected javax.swing.JTextField requester;
    private javax.swing.JButton requesterButton;
    private javax.swing.JLabel resLabel;
    protected javax.swing.JTextPane resolution;
    private javax.swing.JMenuItem saveSettings;
    private javax.swing.JButton searchButton;
    protected javax.swing.JTextField serial;
    protected javax.swing.JTextField serial2;
    protected javax.swing.JTextField serial3;
    protected javax.swing.JTextField serial4;
    protected javax.swing.JSpinner startDate;
    protected javax.swing.JComboBox status;
    protected javax.swing.JTabbedPane tab;
    protected javax.swing.JComboBox technician;
    protected javax.swing.JTextField title;
    protected javax.swing.JComboBox type4;
    // End of variables declaration//GEN-END:variables
}
